<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HeroEngine.Core">
      <HintPath>..\HeroEngine.Core\bin\Debug\net10.0\HeroEngine.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
